[SM-403] Add eth address migration script.
DIMO-Network/users-api pull request #74
Opened 2024-01-08 23:35 UTC by Asfiroth

# Proposed Changes
- Add script to migrate from text column to bytea
- 
### Impacted Routes

### Caveats

2024-01-08 23:38 UTC, elffjs commented on migrations/20240108120235_make_eth_addr_byte_arr.sql
> +        ehtereum_address as eth
```suggestion
        ethereum_address as eth
```

2024-01-08 23:39 UTC, elffjs commented on migrations/20240108120235_make_eth_addr_byte_arr.sql
> +    ALTER COLUMN ehtereum_address SET NOT NULL;
Why?

2024-01-08 23:41 UTC, Asfiroth commented on migrations/20240108120235_make_eth_addr_byte_arr.sql
> +    ALTER COLUMN ehtereum_address SET NOT NULL;
I wasn't sure about this either, if null values are allowed I can remove that last alter.

2024-01-09 20:38 UTC, JamesReate approved these changes
lgtm

2024-01-09 21:27 UTC, Allyson-English approved these changes

2024-01-09 21:30 UTC, elffjs commented on internal/api/users.go
> +		encodedEthAddress := hex.EncodeToString(dbUser.EthereumAddress.Bytes)
This is a breaking change. You want to do `common.BytesToAddress(dbUser.EthereumAddress.Bytes).Hex()`.

2024-01-09 21:34 UTC, elffjs commented on internal/controllers/user_controller.go
> +	addrb := common.HexToAddress(hex.EncodeToString(user.EthereumAddress.Bytes))
Another good use case for [`common.BytesToAddress`](https://pkg.go.dev/github.com/ethereum/go-ethereum/common#BytesToAddress).

2024-01-09 21:35 UTC, elffjs commented on internal/controllers/user_controller.go
> +	if body.Web3.Address.Defined && body.Web3.Address.Value != null.StringFrom(hex.EncodeToString(user.EthereumAddress.Bytes)) {
Can I make some changes to this file before you merge? Some of this is garbage I shouldn't have written. This line in particular is really bad.

2024-01-09 21:36 UTC, Asfiroth commented on internal/controllers/user_controller.go
> +	if body.Web3.Address.Defined && body.Web3.Address.Value != null.StringFrom(hex.EncodeToString(user.EthereumAddress.Bytes)) {
I don't have any issue with that, go ahead.

2024-01-09 21:37 UTC, elffjs requested changes

2024-01-09 21:37 UTC, elffjs commented on internal/controllers/user_controller.go
> +		referrer = null.StringFrom(hex.EncodeToString(user.R.ReferringUser.EthereumAddress.Bytes))
Similarly, I would prefer `common.BytesToAddress(user.R.ReferringUser.EthereumAddress.Bytes).Hex()`. This is probably not going to break anything.

2024-01-09 21:39 UTC, elffjs commented
I think my main issue is the EIP-55 thing. I don't think this is going to play well with that, and a lot of the rest of the system assumes that's going to stay the same. In general I don't think you ever want to use the `hex` package. Go-Ethereum's `common` is usually going to have the behavior you want.

2024-01-09 21:40 UTC, elffjs commented on internal/controllers/user_controller.go
> +	if body.Web3.Address.Defined && body.Web3.Address.Value != null.StringFrom(hex.EncodeToString(user.EthereumAddress.Bytes)) {
In particular, I never should have used `NewMixedcaseAddressFromString`. That was dumb and I want to get rid of that.

2024-01-09 21:41 UTC, elffjs commented on migrations/20240108120235_make_eth_addr_byte_arr.sql
> +-- +goose StatementEnd
Newline.

2024-01-09 21:43 UTC, Asfiroth commented on migrations/20240108120235_make_eth_addr_byte_arr.sql
> +-- +goose StatementEnd
which one, sorry I don't follow

2024-01-09 21:44 UTC, elffjs commented on migrations/20240108120235_make_eth_addr_byte_arr.sql
> +-- +goose StatementEnd
GitHub is complaining because there isn't a newline at the end of the file. Unix says files end in newlines.

2024-01-09 22:11 UTC, elffjs commented on internal/api/users.go
> +		encodedEthAddress := hex.EncodeToString(dbUser.EthereumAddress.Bytes)
This is the most important one. We cannot merge this line as it is.

2024-01-09 22:16 UTC, Asfiroth commented on internal/api/users.go
> +		encodedEthAddress := hex.EncodeToString(dbUser.EthereumAddress.Bytes)
fixed

2024-01-09 22:19 UTC, Asfiroth commented
Hi @elffjs I have made requested changes, please check out on sql script when encoding I'm removing 0x prefix since it makes `decode` function fail. This is assuming that all stored eth addresses have it.
cc. @JamesReate

2024-01-09 22:20 UTC, elffjs commented
All stored addresses have it. I don't think we disagree on this point?

2024-01-09 22:21 UTC, Asfiroth commented
Nope, it just to clarify why it has a `substr` function call there.

2024-01-09 22:25 UTC, elffjs commented on internal/controllers/user_controller.go
> +			ethAddress, err := hex.DecodeString(removeOxPrefix(mixAddr.Address().Hex()))
```suggestion
			ethAddress := mixAddr.Address().Bytes()
```

2024-01-09 22:25 UTC, elffjs commented on internal/controllers/user_controller.go
> +			Address:         null.StringFrom(string(common.BytesToAddress(user.EthereumAddress.Bytes).Hex())),
Why do we need `string(...)` here?

2024-01-09 22:26 UTC, elffjs commented on internal/controllers/user_controller.go
> +		ethAddress, err := hex.DecodeString(removeOxPrefix(mixAddr.Address().Hex()))
```suggestion
		ethAddress := mixAddr.Address().Bytes()
```

2024-01-09 22:30 UTC, Asfiroth commented on internal/controllers/user_controller.go
> +			Address:         null.StringFrom(string(common.BytesToAddress(user.EthereumAddress.Bytes).Hex())),
sorry, my bad, didn't noticed that one

2024-01-10 01:29 UTC, elffjs approved these changes

2024-01-10 14:46 UTC, Asfiroth commented
Hi @elffjs you said you wanted to make some changes/improvements to the current logic here before we merge, we'll wait to merge this until you give us green light to merge 😸

2024-01-10 14:48 UTC, elffjs commented
Just merge it. I will make some edits later.

I am still a bit worried. When I wrote this we were really racing and I didn't test anything. Now it's a mess. Let's see how it looks on dev.

2024-01-10 14:50 UTC, merged

2024-01-10 15:52 UTC, elffjs commented
Seems okay
<img width="328" alt="image" src="https://github.com/DIMO-Network/users-api/assets/79415431/09548dcb-ce4f-45d1-91e6-80ddb5d47f41">